version: '3.9'

services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    expose:
      - "8000"
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - database
      - simulation_node

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway

  simulation_node:
    build:
      context: .
      dockerfile: ./simulation/Dockerfile
    command: ["echo", "Simulation Node image built."]
    deploy:
      replicas: 0

  database:
    image: postgres:latest
    container_name: casino_simulation_db
    restart: always
    environment:
      POSTGRES_USER: casino_user
      POSTGRES_PASSWORD: casino_pass
      POSTGRES_DB: casino_db
    ports:
      - "5433:5432"
    volumes:
      - casino_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  casino_db_data:
