version: '3.9'

services:
  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - simulation_node_1
      - simulation_node_2

  simulation_node_1:
    build:
      context: .
      dockerfile: ./simulation/Dockerfile
    environment:
      SERVER_INSTANCE_ID: simulation_node_1
    volumes:
      - ./logs:/app/logs
      - ./game-servers:/app/game-servers
    depends_on:
      - database

  simulation_node_2:
    build:
      context: .
      dockerfile: ./simulation/Dockerfile
    environment:
      SERVER_INSTANCE_ID: simulation_node_2
    volumes:
      - ./logs:/app/logs
      - ./game-servers:/app/game-servers
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: casino_simulation_db
    restart: always
    environment:
      POSTGRES_USER: casino_user
      POSTGRES_PASSWORD: casino_pass
      POSTGRES_DB: casino_db
    ports:
      - "5433:5432"
    volumes:
      - casino_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  casino_db_data:
